(() => {
  'use strict';
  const KEY='moneyflow-v3', $=id=>document.getElementById(id), today=new Date().toISOString().slice(0,10);
  const defaults=[['Food & Drinks','expense'],['Transportation','expense'],['Family','expense'],['Housing','expense'],['Utilities','expense'],['Shopping','expense'],['Health','expense'],['Education','expense'],['Salary','income'],['Bonus','income']];
  const fallback={transactions:[],categories:defaults.map(([name,type])=>({name,type})),budgets:[],goals:[],loans:[],settings:{theme:'light',syncUrl:'',syncRevision:'',lastSynced:''},reportMonth:today.slice(0,7)};
  let state=load(), syncing=false;
  state.settings=Object.assign({},fallback.settings,state.settings||{});
  state.budgets=Array.isArray(state.budgets)?state.budgets:[];
  state.goals=Array.isArray(state.goals)?state.goals:[];
  state.loans=Array.isArray(state.loans)?state.loans:[];
  state.transactions=Array.isArray(state.transactions)?state.transactions:[];
  state.categories=Array.isArray(state.categories)&&state.categories.length?state.categories:fallback.categories;
  state.currentType=state.currentType||'expense';

  function load(){try{return Object.assign({},fallback,JSON.parse(localStorage.getItem(KEY)||'null')||{})}catch(e){return fallback}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
  function money(n){return `${Math.round(Number(n)||0).toLocaleString()} MMK`}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]))}
  function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('on');clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove('on'),2200)}
  function month(){return state.reportMonth||today.slice(0,7)}
  function items(){return state.transactions.filter(t=>String(t.date||'').slice(0,7)===month())}
  function totals(xs){return xs.reduce((r,t)=>{const n=Number(t.amount)||0;if(t.type==='income')r.income+=n;else if(t.type==='expense')r.expense+=n;else if(t.type==='credit')r.credit+=n;return r},{income:0,expense:0,credit:0})}
  function loanRemaining(id){const loan=state.loans.find(l=>String(l.id)===String(id));return loan?Number(loan.remaining)||0:0}
  function renderLoanSelect(){const el=$('loanSelect');if(!el)return;const active=state.loans.filter(l=>Number(l.remaining)>0);if(!active.length){el.innerHTML='<option value="">No active loan</option>';return;}el.innerHTML=active.map(l=>`<option value="${esc(l.id)}">${esc(l.name||'Loan')} (${money(l.remaining)})</option>`).join('')}
  function greeting(){const h=new Date().getHours(),part=h<12?'Morning':h<17?'Afternoon':h<21?'Evening':'Night';if($('greet'))$('greet').textContent=`GOOD ${part.toUpperCase()}`;if($('greetTitle'))$('greetTitle').textContent=`Welcome back 👋`}
  function setType(type){state.currentType=type;const titles={expense:'Add Expense',income:'Add Income',loan:'Add Loan',payback:'Add Loan Payback',credit:'Add Credit Payment'};if($('formTitle'))$('formTitle').textContent=titles[type]||'Add Entry';if($('amount'))$('amount').value='';if($('note'))$('note').value='';if($('loanSelect'))$('loanSelect').disabled=type!=='payback'}
  function populateCategories(){const s=$('category');if(!s)return;let list=[];if(state.currentType==='payback'){list=state.categories.filter(c=>c.type==='expense');}else{list=state.categories.filter(c=>c.type===state.currentType);}s.innerHTML=list.length?list.map(c=>`<option>${esc(c.name)}</option>`).join(''):'<option>General</option>'}
  function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));}
  function budgetRows(){const spent={};items().filter(t=>t.type==='expense').forEach(t=>spent[t.category||'General']=(spent[t.category||'General']||0)+Number(t.amount||0));return state.budgets.map(b=>{const target=Number(b.amount)||0;const used=spent[b.category]||0;const pct=target?Math.min(100,Math.round(used/target*100)):0;return {category:b.category,amount:target,used,pct}}).filter(b=>b.amount>0)}
  function renderBudgets(){const rows=budgetRows(),html=rows.length?rows.map(b=>`<div class="budget-card ${b.pct>=100?'over':b.pct>=80?'near':''}"><div class="head"><b>${esc(b.category)}</b><strong>${money(b.used)}</strong></div><div class="bar"><i style="width:${Math.min(100,b.pct)}%"></i></div><small>${money(b.amount)} budget</small></div>`).join(''):'<div class="empty">No budgets yet</div>';const el=$('budgets');if(el)el.innerHTML=html}
  function renderGoals(){const html=state.goals.length?state.goals.map((g,i)=>{const pct=g.target?Math.min(100,Number(g.saved||0)/g.target*100):0;return `<div class="goal-card"><div class="head"><b>${esc(g.name)}</b><strong>${money(g.saved||0)}</strong></div><div class="bar"><i style="width:${pct}%"></i></div><small>${money(g.target||0)} target</small></div>`}).join(''):'<div class="empty">No goals yet</div>';const el=$('goals');if(el)el.innerHTML=html}
  function renderReports(){const xs=items(),t=totals(xs),grouped={};xs.filter(x=>x.type==='expense').forEach(x=>grouped[x.category||'General']=(grouped[x.category||'General']||0)+Number(x.amount||0));const top=Object.entries(grouped).sort((a,b)=>b[1]-a[1]).slice(0,5);const html=top.length?top.map(([name,val])=>`<li><span>${esc(name)}</span><b>${money(val)}</b></li>`).join(''):'<li><span>No expense data</span><b>0 MMK</b></li>';const el=$('reportList');if(el)el.innerHTML=html;const cash=$('cashflow');if(cash)cash.textContent=money(t.income-t.expense-t.credit);const sp=$('spent');if(sp)sp.textContent=money(t.expense);const rem=$('remaining');if(rem)rem.textContent=money(t.income-t.expense-t.credit)}
  function render(){greeting();renderLoanSelect();const xs=items(),t=totals(xs),net=t.income-t.expense-t.credit;[['income',t.income],['expense',t.expense],['credit',t.credit],['remaining',net]].forEach(([key,val])=>{const el=$(key);if(el)el.textContent=money(val)});if($('txCount'))$('txCount').textContent=`Activity (${xs.length})`;const list=xs.slice().reverse().map(tx=>`<div class="row"><span>${esc(tx.type.toUpperCase())} ${esc(tx.category||'General')}</span><b class="${tx.type==='income'?'up':'down'}">${tx.type==='income'?'+':'-'}${money(tx.amount)}</b></div>`).join('')||'<div class="empty">No transactions</div>';const el=$('txList');if(el)el.innerHTML=list;renderBudgets();renderGoals();renderReports();theme();}
  function injectPlanningUI(){if($('planningStyles'))return;const st=document.createElement('style');st.id='planningStyles';st.textContent='.planning-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.budget-card,.goal-card,.panel{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:12px}.budget-card .head,.goal-card .head{display:flex;justify-content:space-between;align-items:center}.bar{height:8px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;margin:8px 0}.bar i{display:block;height:100%;background:linear-gradient(90deg,#2dd4bf,#60a5fa);border-radius:inherit}.budget-card.over .bar i{background:linear-gradient(90deg,#ef4444,#f97316)}.budget-card.near .bar i{background:linear-gradient(90deg,#fbbf24,#f59e0b)}';document.head.appendChild(st)}
  function theme(){document.body.classList.toggle('dark',state.settings.theme==='dark');if($('switch'))$('switch').classList.toggle('on',state.settings.theme==='dark')}
  async function api(action,payload={}){if(!state.settings.syncUrl)throw Error('Add the Apps Script URL first.');const r=await fetch(state.settings.syncUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({action},payload))});const out=await r.json().catch(()=>({}));if(!out||!out.ok)throw Error((out&&out.error)||'Sync failed');return out.data||out}
  async function pushChanges(){if(syncing||!state.settings.syncUrl)return;syncing=true;try{const payload={transactions:state.transactions,categories:state.categories,budgets:state.budgets,goals:state.goals,loans:state.loans};const r=await api('replaceAll',payload);state.settings.syncRevision=(r&&r.revision)||state.settings.syncRevision;state.settings.lastSynced=new Date().toISOString();save();toast('Synced to Google Sheets');}catch(e){toast(e.message||'Sync failed')}finally{syncing=false;render()}}
  async function pull(){if(syncing||!state.settings.syncUrl)return;syncing=true;try{const r=await api('getAll');if(r&&r.transactions){state.transactions=r.transactions||[];state.categories=r.categories||[];state.budgets=r.budgets||[];state.goals=r.goals||[];state.loans=r.loans||[];save();toast('Pulled from Google Sheets');}}catch(e){toast(e.message||'Pull failed')}finally{syncing=false;render()}}
  document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p)return show(p.dataset.page);const a=e.target.closest('[data-add]');if(a){setType(a.dataset.add);show('add');return;}const syncBtn=e.target.closest('[data-sync]');if(syncBtn){if(syncBtn.dataset.sync==='push')return pushChanges();if(syncBtn.dataset.sync==='pull')return pull();}})
  $('form')?.addEventListener('submit',e=>{if(e.target.id!=='form')return;e.preventDefault();const amount=Number($('amount').value);if(!amount||amount<=0)return toast('Enter an amount greater than 0');const type=state.currentType;const date=$('date')?$('date').value||today:today;const category=($('category')&&$('category').value)||'General';const note=($('note')&&$('note').value||'').trim();let loanId='';if($('loanSelect'))loanId=$('loanSelect').value||'';const tx={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,type,amount,date,category,note,loanId,createdAt:new Date().toISOString()};if(type==='loan'){tx.type='income';tx.category='Loan';tx.loanId=tx.loanId||`${Date.now()}-${Math.random().toString(16).slice(2)}`;const loan=state.loans.find(l=>String(l.id)===String(tx.loanId));if(loan){loan.principal=(Number(loan.principal)||0)+amount;loan.remaining=(Number(loan.remaining)||0)+amount;loan.name=loan.name||note||'Loan';loan.date=date;loan.note=note||loan.note||'';}else{state.loans.push({id:tx.loanId,name:note||'Loan',principal:amount,remaining:amount,date,note,createdAt:tx.createdAt})}}else if(type==='payback'){tx.type='expense';tx.category='Loan Repayment';if(!loanId){return toast('Select a loan to pay back');}tx.loanId=loanId;const loan=state.loans.find(l=>String(l.id)===String(loanId));if(loan){loan.remaining=Math.max(0,(Number(loan.remaining)||0)-amount);loan.date=date;loan.note=loan.note||note||''}}else{tx.type=type;}
  state.transactions.push(tx);save();render();toast(type==='loan'?'Loan saved':type==='payback'?'Loan payback saved':'Saved');if($('form'))$('form').reset();if($('date'))$('date').value=today;if($('loanSelect'))$('loanSelect').disabled=true;})
  document.addEventListener('submit',e=>{if(e.target.id==='budgetForm'){e.preventDefault();const category=$('budgetCategory').value,amount=Number($('budgetAmount').value);if(!category||amount<=0)return toast('Enter a valid budget amount');state.budgets=state.budgets.filter(b=>b.category!==category);state.budgets.push({category,amount});save();render();toast('Budget saved');}})
  $('month')?.addEventListener('change',e=>{state.reportMonth=e.target.value||today.slice(0,7);save();render()});['theme','switch'].forEach(id=>$(id)?.addEventListener('click',()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();theme()}));
  injectPlanningUI();if($('date'))$('date').value=today;populateCategories();setType(state.currentType);render();show('home');
})();
