(() => {
  'use strict';

  const KEY = 'moneyflow-v3';
  const $ = id => document.getElementById(id);
  const today = new Date().toISOString().slice(0, 10);
  const defaults = [['Food & Drinks','expense'],['Transportation','expense'],['Family','expense'],['Housing','expense'],['Utilities','expense'],['Shopping','expense'],['Health','expense'],['Education','expense'],['Salary','income'],['Bonus','income']];
  const fallback = {transactions:[],categories:defaults.map(([name,type])=>({name,type})),budgets:[],goals:[],loans:[],settings:{theme:'light',syncUrl:'',syncRevision:'',lastSynced:''},reportMonth:today.slice(0,7)};
  let state = load();
  let syncing = false;
  state.settings = Object.assign({}, fallback.settings, state.settings || {});
  state.categories = Array.isArray(state.categories) && state.categories.length ? state.categories : fallback.categories;
  ['budgets','goals','loans','transactions'].forEach(k => { if (!Array.isArray(state[k])) state[k] = []; });
  state.currentType = state.currentType || 'expense';

  function uid(prefix='id') { return `${prefix}-${window.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}`; }
  function load() { try { const raw = JSON.parse(localStorage.getItem(KEY) || 'null') || {}; const base = Object.assign({}, fallback, raw); base.categories = Array.isArray(base.categories) && base.categories.length ? base.categories : fallback.categories; base.budgets = Array.isArray(base.budgets) ? base.budgets : []; base.goals = Array.isArray(base.goals) ? base.goals : []; base.loans = Array.isArray(base.loans) ? base.loans : []; base.transactions = Array.isArray(base.transactions) ? base.transactions.map(tx => tx.type === 'loan' ? Object.assign({}, tx, {type:'income',category:tx.category || 'Loan'}) : tx) : []; return base; } catch (_) { return JSON.parse(JSON.stringify(fallback)); } }
  function save() { try { localStorage.setItem(KEY, JSON.stringify(state)); } catch (_) {} }
  function money(n) { return `${Math.round(Number(n) || 0).toLocaleString()} MMK`; }
  function esc(v) { return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function toast(m) { const e=$('toast'); if(!e)return; e.textContent=m; e.classList.add('on'); clearTimeout(e._timer); e._timer=setTimeout(()=>e.classList.remove('on'),2200); }
  function month() { return state.reportMonth || today.slice(0,7); }
  function items() { return state.transactions.filter(t=>String(t.date||'').slice(0,7)===month()); }
  function totals(xs) { return xs.reduce((r,t)=>{const n=Number(t.amount)||0;if(t.type==='income')r.income+=n;else if(t.type==='expense')r.expense+=n;else if(t.type==='credit')r.credit+=n;return r;},{income:0,expense:0,credit:0}); }
  function show(id) { document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id)); document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); }
  function populateCategories() { const s=$('category'); if(!s)return; const type=state.currentType==='payback'?'expense':state.currentType; const list=state.currentType==='loan'?[{name:'Loan',type:'income'}]:state.categories.filter(c=>c.type===type); s.innerHTML=list.length?list.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join(''):'<option value="General">General</option>'; }
  function setType(type) { state.currentType=type; const titles={expense:'Add Expense',income:'Add Income',loan:'Add Loan',payback:'Add Loan Payback',credit:'Add Credit Payment'}; if($('formTitle'))$('formTitle').textContent=titles[type]||'Add Entry'; if($('amount'))$('amount').value=''; if($('note'))$('note').value=''; if($('loanSelect'))$('loanSelect').disabled=type!=='payback'; if($('loanField'))$('loanField').style.display=type==='payback'?'block':'none'; document.querySelectorAll('.tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.add===type)); populateCategories(); }
  function renderLoanSelect() { const el=$('loanSelect');if(!el)return;const active=state.loans.filter(l=>Number(l.remaining)>0);el.innerHTML=active.length?active.map(l=>`<option value="${esc(l.id)}">${esc(l.name||'Loan')} (${money(l.remaining)})</option>`).join(''):'<option value="">No active loan</option>'; }
  function updateMonthOptions() { const el=$('month');if(!el)return;const months=[...new Set(state.transactions.map(t=>String(t.date||'').slice(0,7)).filter(Boolean))].sort();el.innerHTML=months.length?months.map(m=>`<option value="${m}">${m}</option>`).join(''):'<option value="">Current month</option>'; }
  function greeting() { const h=new Date().getHours(),part=h<12?'Morning':h<17?'Afternoon':h<21?'Evening':'Night';if($('greet'))$('greet').textContent=`GOOD ${part.toUpperCase()}`;if($('greetTitle'))$('greetTitle').textContent='Welcome back 👋';if($('focusSummary'))$('focusSummary').textContent=money(state.transactions.reduce((s,t)=>s+(t.type==='income'?Number(t.amount)||0:0),0));if($('loanSummary'))$('loanSummary').textContent=money(state.loans.reduce((s,l)=>s+(Number(l.remaining)||0),0)); }
  function budgetRows() { const spent={};items().filter(t=>t.type==='expense').forEach(t=>{const k=t.category||'General';spent[k]=(spent[k]||0)+Number(t.amount||0);});return state.budgets.map(b=>{const amount=Number(b.amount)||0,used=spent[b.category]||0;return {category:b.category,amount,used,pct:amount?Math.min(100,Math.round(used/amount*100)):0};}).filter(b=>b.amount>0); }
  function renderBudgets() { const el=$('budgets');if(!el)return;const rows=budgetRows();el.innerHTML=rows.length?rows.map(b=>`<div class="budget-card ${b.pct>=100?'over':b.pct>=80?'near':''}"><div class="head"><b>${esc(b.category)}</b><strong>${money(b.used)}</strong></div><div class="bar"><i style="width:${b.pct}%"></i></div><small>${money(b.amount)} budget</small></div>`).join(''):'<div class="empty">No budgets yet</div>'; }
  function renderGoals() { const el=$('goals');if(!el)return;el.innerHTML=state.goals.length?state.goals.map(g=>{const pct=g.target?Math.min(100,Number(g.saved||0)/Number(g.target)*100):0;return `<div class="goal-card"><div class="head"><b>${esc(g.name)}</b><strong>${money(g.saved)}</strong></div><div class="bar"><i style="width:${pct}%"></i></div><small>${money(g.target)} target</small></div>`;}).join(''):'<div class="empty">No goals yet</div>'; }
  function renderReports() { const t=totals(items());if($('cashflow'))$('cashflow').textContent=money(t.income-t.expense-t.credit);if($('spent'))$('spent').textContent=money(t.expense);if($('remaining'))$('remaining').textContent=money(t.income-t.expense-t.credit); }
  function theme() { document.body.classList.toggle('dark',state.settings.theme==='dark');if($('switch'))$('switch').classList.toggle('on',state.settings.theme==='dark'); }
  function render() { greeting();renderLoanSelect();updateMonthOptions();const xs=items(),t=totals(xs),net=t.income-t.expense-t.credit;[['income',t.income],['expense',t.expense],['credit',t.credit],['remaining',net]].forEach(([k,v])=>{if($(k))$(k).textContent=money(v);});if($('txCount'))$('txCount').textContent=`Activity (${xs.length})`;if($('txList'))$('txList').innerHTML=xs.slice().reverse().map(tx=>`<div class="row"><span>${esc(tx.type.toUpperCase())} ${esc(tx.category||'General')}</span><b class="${tx.type==='income'?'up':'down'}">${tx.type==='income'?'+':'-'}${money(tx.amount)}</b></div>`).join('')||'<div class="empty">No transactions</div>';renderBudgets();renderGoals();renderReports();theme();}

  function injectPlanningUI() {
    if ($('planningStyles')) return;
    const style=document.createElement('style');style.id='planningStyles';style.textContent='.planning-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.budget-card,.goal-card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:12px}.budget-card .head,.goal-card .head{display:flex;justify-content:space-between;align-items:center}.bar{height:8px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;margin:8px 0}.bar i{display:block;height:100%;background:linear-gradient(90deg,#2dd4bf,#60a5fa);border-radius:inherit}.budget-card.over .bar i{background:#ef4444}.budget-card.near .bar i{background:#f59e0b}@media(max-width:760px){.planning-grid{grid-template-columns:1fr}}';document.head.appendChild(style);
    const settings=$('settings');if(!settings)return;
    const panel=document.createElement('div');panel.className='panel';panel.innerHTML=`<div class="head"><div><small>PLANNING</small><h2>Budgets & Goals</h2></div></div><div class="planning-grid"><form id="budgetForm"><label>Budget category<select id="budgetCategory"></select></label><label>Monthly amount<input id="budgetAmount" inputmode="decimal" required></label><button type="submit">Save budget</button></form><form id="goalForm"><label>Goal name<input id="goalName" required></label><label>Target amount<input id="goalTarget" inputmode="decimal" required></label><label>Saved amount<input id="goalSaved" inputmode="decimal" value="0"></label><button type="submit">Save goal</button></form></div>`;settings.appendChild(panel);
  }
  async function api(action,payload={}) { if(!state.settings.syncUrl)throw Error('Add the Apps Script URL first.');const r=await fetch(state.settings.syncUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({action},payload))});const out=await r.json().catch(()=>({}));if(!out.ok)throw Error(out.error||'Sync failed');return out.data||out; }
  async function pushChanges() { if(syncing||!state.settings.syncUrl)return;syncing=true;try{const r=await api('replaceAll',{transactions:state.transactions,categories:state.categories,budgets:state.budgets,goals:state.goals,loans:state.loans});state.settings.syncRevision=r.revision||state.settings.syncRevision;state.settings.lastSynced=new Date().toISOString();save();toast('Synced to Google Sheets');}catch(e){toast(e.message||'Sync failed');}finally{syncing=false;render();} }
  async function pull() { if(syncing||!state.settings.syncUrl)return;syncing=true;try{const r=await api('getAll');if(r&&Array.isArray(r.transactions)){state.transactions=r.transactions;state.categories=Array.isArray(r.categories)?r.categories:[];state.budgets=Array.isArray(r.budgets)?r.budgets:[];state.goals=Array.isArray(r.goals)?r.goals:[];state.loans=Array.isArray(r.loans)?r.loans:[];state.settings.syncRevision=r.revision||state.settings.syncRevision;state.settings.lastSynced=new Date().toISOString();save();bindUI();toast('Pulled from Google Sheets');}}catch(e){toast(e.message||'Pull failed');}finally{syncing=false;render();} }
  function bindUI() { if($('syncUrl'))$('syncUrl').value=state.settings.syncUrl||'';const s=$('budgetCategory');if(s){const cats=state.categories.filter(c=>c.type==='expense');s.innerHTML=cats.length?cats.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join(''):'<option value="General">General</option>';}}

  document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page)return show(page.dataset.page);const add=e.target.closest('[data-add]');if(add){setType(add.dataset.add);show('add');return;}const sync=e.target.closest('[data-sync]');if(sync){if(sync.dataset.sync==='push')pushChanges();if(sync.dataset.sync==='pull')pull();}});
  document.addEventListener('submit',e=>{
    if(e.target.id==='budgetForm'){e.preventDefault();const category=$('budgetCategory').value,amount=Number(String($('budgetAmount').value).replace(/,/g,''));if(!category||amount<=0)return toast('Enter a valid budget amount');state.budgets=state.budgets.filter(b=>b.category!==category);state.budgets.push({category,amount});save();render();e.target.reset();toast('Budget saved');return;}
    if(e.target.id==='goalForm'){e.preventDefault();const name=$('goalName').value.trim(),target=Number(String($('goalTarget').value).replace(/,/g,'')),saved=Number(String($('goalSaved').value||0).replace(/,/g,''));if(!name||target<=0||saved<0)return toast('Enter a valid goal');const existing=state.goals.find(g=>g.name.toLowerCase()===name.toLowerCase());if(existing){existing.target=target;existing.saved=saved;}else state.goals.push({name,target,saved});save();render();e.target.reset();toast('Goal saved');return;}
    if(e.target.id==='form'){e.preventDefault();const amount=Number(String($('amount').value).replace(/,/g,''));if(!amount||amount<=0)return toast('Enter an amount greater than 0');const type=state.currentType,date=$('date')?.value||today,note=($('note')?.value||'').trim();let loanId=$('loanSelect')?.value||'';const tx={id:uid('tx'),type,amount,date,category:$('category')?.value||'General',note,loanId,createdAt:new Date().toISOString()};if(type==='loan'){tx.type='income';tx.category='Loan';tx.loanId=uid('loan');state.loans.push({id:tx.loanId,name:note||'Loan',principal:amount,remaining:amount,date,note,createdAt:tx.createdAt});}else if(type==='payback'){if(!loanId)return toast('Select a loan to pay back');tx.type='expense';tx.category='Loan Repayment';const loan=state.loans.find(l=>String(l.id)===String(loanId));if(!loan)return toast('Selected loan was not found');if(amount>Number(loan.remaining||0))return toast('Payback cannot exceed remaining loan');loan.remaining=Math.max(0,Number(loan.remaining||0)-amount);}state.transactions.push(tx);save();render();toast(type==='loan'?'Loan saved':type==='payback'?'Loan payback saved':'Saved');e.target.reset();if($('date'))$('date').value=today;if($('loanSelect'))$('loanSelect').disabled=true;}
  });
  ['theme','switch'].forEach(id=>$(id)?.addEventListener('click',()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();theme();}));
  document.addEventListener('change',e=>{if(e.target?.id==='syncUrl'){state.settings.syncUrl=e.target.value.trim();save();}});
  injectPlanningUI();bindUI();if($('date'))$('date').value=today;setType(state.currentType);render();show('home');
})();
