(() => {
  'use strict';
  const KEY='moneyflow-v3', $=id=>document.getElementById(id), today=new Date().toISOString().slice(0,10);
  const defaults=[['Food & Drinks','expense'],['Transportation','expense'],['Family','expense'],['Housing','expense'],['Utilities','expense'],['Shopping','expense'],['Health','expense'],['Education','expense']];
  const fallback={transactions:[],categories:defaults.map(([name,type])=>({name,type})),budgets:[],goals:[],settings:{theme:'light',syncUrl:'',syncRevision:'',lastSynced:''},reportMonth:today.slice(0,7),currentType:'expense'};
  let state=load(), syncing=false;
  state.settings=Object.assign({},fallback.settings,state.settings||{}); state.budgets=Array.isArray(state.budgets)?state.budgets:[]; state.goals=Array.isArray(state.goals)?state.goals:[]; state.currentType=state.currentType||'expense'; state.reportMonth=state.reportMonth||today.slice(0,7);
  function load(){try{return Object.assign({},fallback,JSON.parse(localStorage.getItem(KEY)||'null')||{})}catch(e){return fallback}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
  function money(n){return `${Math.round(Number(n)||0).toLocaleString()} MMK`}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('on');clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove('on'),2200)}
  function month(){return state.reportMonth||today.slice(0,7)}
  function items(){return state.transactions.filter(t=>String(t.date||'').slice(0,7)===month())}
  function totals(xs){return xs.reduce((r,t)=>{const n=Number(t.amount)||0;if(t.type==='income')r.income+=n;else if(t.type==='expense')r.expense+=n;else if(t.type==='loan')r.loan+=n;else if(t.type==='credit')r.credit+=n;return r},{income:0,expense:0,loan:0,credit:0})}
  function greeting(){const h=new Date().getHours(),part=h<12?'Morning':h<17?'Afternoon':h<21?'Evening':'Night';if($('greet'))$('greet').textContent=`GOOD ${part.toUpperCase()}`;if($('greetTitle'))$('greetTitle').textContent=`Good ${part}, welcome back 👋`;if($('focusMsg'))$('focusMsg').textContent=`Stay intentional with your money this ${part.toLowerCase()}.`}
  function setType(type){state.currentType=type;const titles={expense:'Add Expense',income:'Add Income',loan:'Add Loan Payment',credit:'Add Credit Payment'};if($('formTitle'))$('formTitle').textContent=titles[type]||'Add Transaction';document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));populateCategories()}
  function populateCategories(){const s=$('category');if(!s)return;const list=state.categories.filter(c=>c.type===state.currentType);s.innerHTML=list.map(c=>`<option>${esc(c.name)}</option>`).join('')||'<option>General</option>'}
  function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));window.scrollTo(0,0)}
  function budgetRows(){const spent={};items().filter(t=>t.type==='expense').forEach(t=>spent[t.category||'General']=(spent[t.category||'General']||0)+Number(t.amount||0));return state.budgets.map(b=>{const used=spent[b.category]||0,pct=b.amount?used/b.amount*100:0;return Object.assign({},b,{used,pct})})}
  function renderBudgets(){const rows=budgetRows(),html=rows.length?rows.map(b=>`<div class="budget-card ${b.pct>=100?'over':b.pct>=80?'near':''}"><div class="head"><b>${esc(b.category)}</b><strong>${money(b.used)} / ${money(b.amount)}</strong></div><div class="progress"><i style="width:${Math.min(100,b.pct)}%"></i></div><small>${b.pct>=100?'Over budget':b.pct>=80?'Nearly consumed':`${Math.round(b.pct)}% used`}</small></div>`).join(''):'<p class="muted">No budgets yet. Add one below.</p>';['budgets','homeBudgets'].forEach(id=>{if($(id))$(id).innerHTML=html});const alerts=rows.filter(b=>b.pct>=80);if(alerts.length&&state._alertMonth!==month()){state._alertMonth=month();save();toast(alerts.some(b=>b.pct>=100)?'Budget alert: a category is over budget.':'Budget alert: a category is nearly consumed.')}}
  function renderGoals(){const html=state.goals.length?state.goals.map((g,i)=>{const pct=g.target?Math.min(100,Number(g.saved||0)/g.target*100):0;return `<div class="goal-card"><div class="head"><b>${esc(g.name)}</b><button data-goal-remove="${i}">✕</button></div><strong>${money(g.saved)} <small>of ${money(g.target)}</small></strong><div class="progress"><i style="width:${pct}%"></i></div><small>${Math.round(pct)}% complete</small></div>`}).join(''):'<p class="muted">Create a goal to give your savings a direction.</p>';['goals','homeGoals'].forEach(id=>{if($(id))$(id).innerHTML=html})}
  function renderReports(){const xs=items(),t=totals(xs),grouped={};xs.filter(x=>x.type==='expense').forEach(x=>grouped[x.category||'General']=(grouped[x.category||'General']||0)+Number(x.amount||0));const sorted=Object.entries(grouped).sort((a,b)=>b[1]-a[1]),top=sorted[0],largest=xs.slice().sort((a,b)=>(Number(b.amount)||0)-(Number(a.amount)||0))[0];if($('cashflow'))$('cashflow').textContent=money(t.income-t.expense-t.loan-t.credit);if($('topSpend'))$('topSpend').textContent=top?top[0]:'—';if($('topAmt'))$('topAmt').textContent=top?money(top[1]):'0 MMK';if($('largest'))$('largest').textContent=largest?largest.category:'—';if($('largestAmt'))$('largestAmt').textContent=largest?money(largest.amount):'0 MMK';if($('rhythm'))$('rhythm').textContent=String(xs.length);if($('pulse'))$('pulse').innerHTML=sorted.map(([n,v])=>`<div class="row"><span>${esc(n)}</span><b>${money(v)}</b></div>`).join('')||'<p class="muted">No category spending this month.</p>';if($('focusBI'))$('focusBI').innerHTML=`<div class="focusrow"><b>${top?'Watch '+esc(top[0]):'No activity'}</b><small>${top?money(top[1])+' spent this month':'Add a transaction to see reports.'}</small></div>`}
  function render(){greeting();const xs=items(),t=totals(xs),net=t.income-t.expense-t.loan-t.credit;[['income',t.income],['expense',t.expense],['loan',t.loan],['credit',t.credit],['remaining',net]].forEach(([id,n])=>{if($(id))$(id).textContent=money(n)});if($('month'))$('month').value=month();const grouped={};xs.filter(x=>x.type==='expense').forEach(x=>grouped[x.category||'General']=(grouped[x.category||'General']||0)+Number(x.amount||0));const sorted=Object.entries(grouped).sort((a,b)=>b[1]-a[1]);if($('breakdown'))$('breakdown').innerHTML=sorted.map(([n,v])=>`<div class="row"><span>${esc(n)}</span><b>${money(v)}</b></div>`).join('')||'<p class="muted">No expenses this month.</p>';if($('recent'))$('recent').innerHTML=state.transactions.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5).map(x=>`<div class="row"><span>${esc(x.category||'General')}<small>${esc(x.date||'')}</small></span><b>${x.type==='income'?'+':'−'}${money(x.amount)}</b></div>`).join('')||'<p class="muted">Your recent activity will appear here.</p>';if($('rows'))$('rows').innerHTML=state.transactions.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map((x,i)=>`<tr><td>${esc(x.date)}</td><td><b>${esc(x.category||'General')}</b><small>${esc(x.note||x.type)}</small></td><td>${x.type==='income'?'+':'−'}${money(x.amount)}</td><td><button data-remove="${i}">✕</button></td></tr>`).join('');if($('txCount'))$('txCount').textContent=`Activity (${state.transactions.length})`;if($('cats'))$('cats').innerHTML=state.categories.map((c,i)=>`<div class="cat"><span>${esc(c.name)}</span><small>${esc(c.type)}</small><button data-cat-remove="${i}">✕</button></div>`).join('');if($('syncUrl')&&document.activeElement!==$('syncUrl'))$('syncUrl').value=state.settings.syncUrl||'';if($('syncStatus'))$('syncStatus').textContent=state.settings.syncUrl?(syncing?'Syncing…':'Up to date'):'Local only';if($('syncText'))$('syncText').textContent=state.settings.lastSynced?`Last synced: ${state.settings.lastSynced}`:'Configure Google Apps Script in Settings.';theme();populateCategories();renderReports();renderBudgets();renderGoals()}
  function injectPlanningUI(){if($('planningStyles'))return;const st=document.createElement('style');st.id='planningStyles';st.textContent='.planning-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.budget-card,.goal-card{padding:14px;border:1px solid var(--line);border-radius:14px;margin:8px 0}.budget-card.near{border-color:#eab308}.budget-card.over{border-color:#ef4444;background:#fff1f2}.goal-card strong{display:block;margin:8px 0}.muted{color:var(--muted)}';document.head.appendChild(st);const settings=document.getElementById('settings'),home=document.getElementById('home');if(settings&&!$('planning')){const box=document.createElement('div');box.id='planning';box.className='panel';box.innerHTML='<h2>Budget & Goal Planning</h2><div class="planning-grid"><div><h3>Category budget</h3><form id="budgetForm"><select id="budgetCategory"></select><input id="budgetAmount" type="number" min="1" placeholder="Monthly limit" required><button class="primary">Save budget</button></form><div id="budgets"></div></div><div><h3>Savings goal</h3><form id="goalForm"><input id="goalName" placeholder="Goal name" required><input id="goalTarget" type="number" min="1" placeholder="Target amount" required><input id="goalSaved" type="number" min="0" placeholder="Already saved"><button class="primary">Save goal</button></form><div id="goals"></div></div></div>';settings.insertBefore(box,settings.firstElementChild.nextElementSibling)}if(home&&!$('homePlanning')){const box=document.createElement('div');box.id='homePlanning';box.className='planning-grid';box.innerHTML='<div class="panel"><div class="head"><h2>Budget health</h2><button data-page="settings">Manage</button></div><div id="homeBudgets"></div></div><div class="panel"><div class="head"><h2>Goals</h2><button data-page="settings">Plan</button></div><div id="homeGoals"></div></div>';home.appendChild(box)}const s=$('budgetCategory');if(s)s.innerHTML=state.categories.filter(c=>c.type==='expense').map(c=>`<option>${esc(c.name)}</option>`).join('')||'<option>General</option>'}
  function theme(){document.body.classList.toggle('dark',state.settings.theme==='dark');if($('switch'))$('switch').classList.toggle('on',state.settings.theme==='dark')}
  async function api(action,payload={}){if(!state.settings.syncUrl)throw Error('Add the Apps Script URL first.');const r=await fetch(state.settings.syncUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(Object.assign({action},payload))});if(!r.ok)throw Error(`Network error: ${r.status}`);const d=await r.json();if(!d.ok)throw Error(d.message||'Sync failed');return d}
  async function pushChanges(){if(syncing||!state.settings.syncUrl)return;syncing=true;render();try{const r=await api('replaceAll',{transactions:state.transactions,categories:state.categories,budgets:state.budgets,goals:state.goals});state.settings.syncRevision=r.data?.revision||'';state.settings.lastSynced=new Date().toLocaleString();save();toast('Synced to Google Sheets.')}catch(e){toast(e.message)}finally{syncing=false;render()}}
  async function pull(){if(syncing||!state.settings.syncUrl)return;syncing=true;render();try{const r=await api('getAll');if(r.data){state.transactions=r.data.transactions||[];state.categories=r.data.categories?.length?r.data.categories:state.categories;state.budgets=r.data.budgets||[];state.goals=r.data.goals||[];save();toast('Data pulled from Google Sheets.')}}catch(e){toast(e.message)}finally{syncing=false;render()}}
  document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p)return show(p.dataset.page);const a=e.target.closest('[data-add]');if(a){setType(a.dataset.add);show('add');return}const ty=e.target.closest('[data-type]');if(ty)return setType(ty.dataset.type);const ri=e.target.closest('[data-remove]');if(ri){state.transactions.splice(Number(ri.dataset.remove),1);save();render();pushChanges();return}const cr=e.target.closest('[data-cat-remove]');if(cr){state.categories.splice(Number(cr.dataset.catRemove),1);save();render();return}const gr=e.target.closest('[data-goal-remove]');if(gr){state.goals.splice(Number(gr.dataset.goalRemove),1);save();render();return}});
  $('form')?.addEventListener('submit',e=>{if(e.target.id!=='form')return;e.preventDefault();const amount=Number($('amount').value);if(!amount||amount<=0)return toast('Enter an amount greater than zero.');state.transactions.push({id:Date.now().toString(),type:state.currentType,amount,date:$('date').value||today,category:$('category').value||'General',note:$('note').value,createdAt:new Date().toISOString()});save();e.target.reset();$('date').value=today;render();pushChanges();show('home')});
  document.addEventListener('submit',e=>{if(e.target.id==='budgetForm'){e.preventDefault();const category=$('budgetCategory').value,amount=Number($('budgetAmount').value);if(!category||amount<=0)return toast('Enter a valid budget.');state.budgets=state.budgets.filter(b=>b.category!==category);state.budgets.push({category,amount});save();render();pushChanges()}if(e.target.id==='goalForm'){e.preventDefault();const name=$('goalName').value.trim(),target=Number($('goalTarget').value);if(!name||target<=0)return toast('Enter a valid goal.');state.goals.push({name,target,saved:Number($('goalSaved').value)||0});save();render();pushChanges()}});
  $('month')?.addEventListener('change',e=>{state.reportMonth=e.target.value||today.slice(0,7);save();render()});['theme','switch'].forEach(id=>$(id)?.addEventListener('click',()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();render()}));$('syncUrl')?.addEventListener('change',e=>{state.settings.syncUrl=e.target.value.trim();save();render()});$('push')?.addEventListener('click',pushChanges);$('pull')?.addEventListener('click',pull);$('test')?.addEventListener('click',pull);$('addCat')?.addEventListener('click',()=>{const name=$('newCat').value.trim();if(!name)return toast('Enter a category name.');state.categories.push({name,type:$('newType').value,createdAt:new Date().toISOString()});$('newCat').value='';save();injectPlanningUI();render();pushChanges()});$('clear')?.addEventListener('click',()=>{if(confirm('Delete all local transactions?')){state.transactions=[];save();render();pushChanges()}});
  injectPlanningUI();if($('date'))$('date').value=today;setType(state.currentType);render();show('home');
})();
